# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code. Used by Github Pages.

name: Node.js Github Pages CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: NodeJS 18 Yarn
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
    - run: yarn install
    - run: yarn run build
    - name: Setup Pages
      uses: actions/configure-pages@v1
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: './dist'
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
