# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and deploys to Github Pages

name: Node.js Github Pages Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3
      - name: NodeJS 19
        uses: actions/setup-node@v3
        with:
          node-version: "19"
          cache: "npm"
      - run: npm ci
        # Base URL liegt unter yasp.dev (Wegen Org Github Page)
      - run: npm run build --base=/EE-Monitor/
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "./dist"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
